// 所属模块
export const MOCK_MODULE_DATA = {
  nodeId: 'rootModule',
  isRoot: true,
  nodeName: 'rootModule',
  children: [
    {
      nodeId: 'r-c630963n6m8dkrtt2o2g',
      isRoot: false,
      nodeName: 'module',
      children: [
        {
          nodeId: 'r-c630963n6m8dkrtt2o2g',
          isRoot: false,
          nodeName: 'tf-instances',
          children: [],
          resourcesList: null,
        },
      ],
      resourcesList: null,
    },
  ],
  resourcesList: null,
};

// Provider
export const MOCK_PROVIDER_DATA = [
  {
    nodeName: 'alicloud',
    list: [
      {
        id: 'r-c630963n6m8dkrtt2o30',
        orgId: 'org-c5t02urn6m889h3uv8kg',
        projectId: 'p-c5t03ebn6m889h3uv8mg',
        envId: 'env-c62vnrbn6m83u8g05k70',
        taskId: 'run-c6307vjn6m8dkrtt2nug',
        provider: 'alicloud',
        module: 'tf-instances',
        address:
          'module.tf-instances.module.tf-instances.alicloud_instance.this[0]',
        type: 'alicloud_instance',
        name: 'this',
        index: '0',
        sensitiveKeys: ['password'],
      },
      {
        id: 'r-c630963n6m8dkrtt2o3g',
        orgId: 'org-c5t02urn6m889h3uv8kg',
        projectId: 'p-c5t03ebn6m889h3uv8mg',
        envId: 'env-c62vnrbn6m83u8g05k70',
        taskId: 'run-c6307vjn6m8dkrtt2nug',
        provider: 'alicloud',
        module: 'tf-instances',
        address:
          'module.tf-instances.module.tf-instances.alicloud_instance.this[1]',
        type: 'alicloud_instance',
        name: 'this',
        index: '1',
        sensitiveKeys: ['password'],
      },
      {
        id: 'r-c630963n6m8dkrtt2o40',
        orgId: 'org-c5t02urn6m889h3uv8kg',
        projectId: 'p-c5t03ebn6m889h3uv8mg',
        envId: 'env-c62vnrbn6m83u8g05k70',
        taskId: 'run-c6307vjn6m8dkrtt2nug',
        provider: 'alicloud',
        module: 'tf-instances',
        address:
          'module.tf-instances.module.tf-instances.alicloud_instance.this[2]',
        type: 'alicloud_instance',
        name: 'this',
        index: '2',
        sensitiveKeys: ['password'],
      },
      {
        id: 'r-c630963n6m8dkrtt2o10',
        orgId: 'org-c5t02urn6m889h3uv8kg',
        projectId: 'p-c5t03ebn6m889h3uv8mg',
        envId: 'env-c62vnrbn6m83u8g05k70',
        taskId: 'run-c6307vjn6m8dkrtt2nug',
        provider: 'alicloud',
        module: 'tf-instances',
        address: 'module.tf-instances.alicloud_security_group.default',
        type: 'alicloud_security_group',
        name: 'default',
        index: '',
      },
      {
        id: 'r-c630963n6m8dkrtt2o1g',
        orgId: 'org-c5t02urn6m889h3uv8kg',
        projectId: 'p-c5t03ebn6m889h3uv8mg',
        envId: 'env-c62vnrbn6m83u8g05k70',
        taskId: 'run-c6307vjn6m8dkrtt2nug',
        provider: 'alicloud',
        module: 'tf-instances',
        address:
          'module.tf-instances.alicloud_security_group_rule.allow_all_tcp',
        type: 'alicloud_security_group_rule',
        name: 'allow_all_tcp',
        index: '',
      },
      {
        id: 'r-c630963n6m8dkrtt2o20',
        orgId: 'org-c5t02urn6m889h3uv8kg',
        projectId: 'p-c5t03ebn6m889h3uv8mg',
        envId: 'env-c62vnrbn6m83u8g05k70',
        taskId: 'run-c6307vjn6m8dkrtt2nug',
        provider: 'alicloud',
        module: 'tf-instances',
        address: 'module.tf-instances.alicloud_vpc.vpc',
        type: 'alicloud_vpc',
        name: 'vpc',
        index: '',
      },
      {
        id: 'r-c630963n6m8dkrtt2o2g',
        orgId: 'org-c5t02urn6m889h3uv8kg',
        projectId: 'p-c5t03ebn6m889h3uv8mg',
        envId: 'env-c62vnrbn6m83u8g05k70',
        taskId: 'run-c6307vjn6m8dkrtt2nug',
        provider: 'alicloud',
        module: 'tf-instances',
        address: 'module.tf-instances.alicloud_vswitch.vsw',
        type: 'alicloud_vswitch',
        name: 'vsw',
        index: '',
      },
    ],
  },
];

// 资源类型
export const MOCK_TYPE_DATA = [
  {
    nodeName: 'alicloud',
    List: [
      {
        id: 'r-c630963n6m8dkrtt2o30',
        orgId: 'org-c5t02urn6m889h3uv8kg',
        projectId: 'p-c5t03ebn6m889h3uv8mg',
        envId: 'env-c62vnrbn6m83u8g05k70',
        taskId: 'run-c6307vjn6m8dkrtt2nug',
        provider: 'alicloud',
        module: 'tf-instances',
        address:
          'module.tf-instances.module.tf-instances.alicloud_instance.this[0]',
        type: 'alicloud_instance',
        name: 'this',
        index: '0',
        sensitiveKeys: ['password'],
      },
      {
        id: 'r-c630963n6m8dkrtt2o3g',
        orgId: 'org-c5t02urn6m889h3uv8kg',
        projectId: 'p-c5t03ebn6m889h3uv8mg',
        envId: 'env-c62vnrbn6m83u8g05k70',
        taskId: 'run-c6307vjn6m8dkrtt2nug',
        provider: 'alicloud',
        module: 'tf-instances',
        address:
          'module.tf-instances.module.tf-instances.alicloud_instance.this[1]',
        type: 'alicloud_instance',
        name: 'this',
        index: '1',
        sensitiveKeys: ['password'],
      },
      {
        id: 'r-c630963n6m8dkrtt2o40',
        orgId: 'org-c5t02urn6m889h3uv8kg',
        projectId: 'p-c5t03ebn6m889h3uv8mg',
        envId: 'env-c62vnrbn6m83u8g05k70',
        taskId: 'run-c6307vjn6m8dkrtt2nug',
        provider: 'alicloud',
        module: 'tf-instances',
        address:
          'module.tf-instances.module.tf-instances.alicloud_instance.this[2]',
        type: 'alicloud_instance',
        name: 'this',
        index: '2',
        sensitiveKeys: ['password'],
      },
      {
        id: 'r-c630963n6m8dkrtt2o10',
        orgId: 'org-c5t02urn6m889h3uv8kg',
        projectId: 'p-c5t03ebn6m889h3uv8mg',
        envId: 'env-c62vnrbn6m83u8g05k70',
        taskId: 'run-c6307vjn6m8dkrtt2nug',
        provider: 'alicloud',
        module: 'tf-instances',
        address: 'module.tf-instances.alicloud_security_group.default',
        type: 'alicloud_security_group',
        name: 'default',
        index: '',
      },
      {
        id: 'r-c630963n6m8dkrtt2o1g',
        orgId: 'org-c5t02urn6m889h3uv8kg',
        projectId: 'p-c5t03ebn6m889h3uv8mg',
        envId: 'env-c62vnrbn6m83u8g05k70',
        taskId: 'run-c6307vjn6m8dkrtt2nug',
        provider: 'alicloud',
        module: 'tf-instances',
        address:
          'module.tf-instances.alicloud_security_group_rule.allow_all_tcp',
        type: 'alicloud_security_group_rule',
        name: 'allow_all_tcp',
        index: '',
      },
      {
        id: 'r-c630963n6m8dkrtt2o20',
        orgId: 'org-c5t02urn6m889h3uv8kg',
        projectId: 'p-c5t03ebn6m889h3uv8mg',
        envId: 'env-c62vnrbn6m83u8g05k70',
        taskId: 'run-c6307vjn6m8dkrtt2nug',
        provider: 'alicloud',
        module: 'tf-instances',
        address: 'module.tf-instances.alicloud_vpc.vpc',
        type: 'alicloud_vpc',
        name: 'vpc',
        index: '',
      },
      {
        id: 'r-c630963n6m8dkrtt2o2g',
        orgId: 'org-c5t02urn6m889h3uv8kg',
        projectId: 'p-c5t03ebn6m889h3uv8mg',
        envId: 'env-c62vnrbn6m83u8g05k70',
        taskId: 'run-c6307vjn6m8dkrtt2nug',
        provider: 'alicloud',
        module: 'tf-instances',
        address: 'module.tf-instances.alicloud_vswitch.vsw',
        type: 'alicloud_vswitch',
        name: 'vsw',
        index: '',
      },
    ],
  },
];
